---
title: "Pr2 OPC"
author: "Gonzalo Sanz"
date: "26/2/2020"
output: html_document
---

```{r}
# PREGUNTA 1: ¿Cuál es la frecuencia del monitor? El tiempo de refresco es de 2 segundos  
#  ¿Cuántos registros y cuántas variables hay?  Existen 8 variables y existen 30 registros

# PREGUNTA 2: Cuál es el tiempo de monitorización en total? ya que la primera medida es 11:58:23 y la ult es 11:59:21
# Se trata de 1 minuto o 58 segundos
getwd()
setwd("C:/Users/Gonzalo Sanz/Documents/ECO")# Esta es la localizacion del WS
datosSAR<-read.csv("sarprueba.csv", stringsAsFactors=FALSE, dec=",")
#View(datosSSAR) Habiendo 31 el calculo de la media y 8 variables
str(datosSAR)
```

Instalamos la libreria dplyr

```{r}
library(dplyr)
```


```{r pressure}
#Cambiamos el nombre de la primera columna y la cambiamos por horas
datosSAR<-rename(datosSAR, Horas=X11.58.21)
# Pone la fila 31 el nombre de mediasSAR
mediasSAR<-datosSAR[31,]
#Quitamos la linea 31 de nuestra BBDD
datosSAR<-datosSAR[-31,]
# Quitamos la segunda columna de la BBDD
datosSAR<-datosSAR[,-2]
```

```{r}
# Creamos una nueva tabla con solo las columnas user y systemm
datosUS<-select(datosSAR, X.user, X.system)

# Hace un plot de la tabla respecto al x.user
plot(datosUS$X.user, type='l', col='red')
# Seguido del x.system
plot(datosUS$X.system,type='l',col='blue')
```


```{r}

# Hacemos un histograma teniendo el eje x.user y despues el system en distintos colores

hist(datosUS$X.user, col='red')

hist(datosUS$X.system,col='blue')

```



```{r}
# Quitamos la linea 25 que es la que nos daba problemas ya que era el valor mas alto y asignamos la eje x la columna de user y al y el de system
datosUS<-datosUS[-25,]
X<-datosUS$X.user 
Y<-datosUS$X.system

# Creamos una grafica de puntos ("p") y despues ponemos la leyenda de nuestra grafica
plot(X, Y, type="p", xlab="USUARIO", ylab="SISTEMA",col="red")
title("Relaccion %usuario y %sistema")
```

```{r}
# Hacemos la media con el eje y, luego lo asignamos a msistema y mostramos los datos
msistema<-mean(datosUS$X.system)
str(mediasSAR)


# Creamos una variable msistemareal la cual contiene el valor del x.system que equivale a 1.38
msistemareal<-mediasSAR$X.system

# Hacemos la media aritmetrica recortada del user y la guardamos el una variable 
musuario<-mean(datosUS$X.user)

# Ahora creamos musuarioreal con el eje x.user
musuarioreal<-mediasSAR$X.user

```

```{r}

#Creamos una tabla(vector, deben de ser iguales en el numero de filas /columnas) unicamente con las 2 variables msistema y msistemareal
df.sistema<-data.frame(msistema, msistemareal)

# Creamos una tabla(los vectorres deben de ser iguales en el numero de filas /columnas) unicamente con las 2 variables msistema y msistemareal
df.usuario<-data.frame(musuario, musuarioreal)

# Creamos una tabla para comparar las dos anteriores 
df.tabla<-data.frame(df.sistema, df.usuario)

# Calculamos el error 
ErrorUsuarioReal<-abs(mean(datosSAR$X.system)-musuarioreal)

# Calculamos el error suavizado
ErrorUsuarioSuavizado<-abs(mean(datosSAR$X.user)-musuario)

print(df.tabla)
print(ErrorUsuarioReal)
print(ErrorUsuarioSuavizado)
```
